# Generated by Django 4.2.17 on 2026-02-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('category__in', ['billing', 'technical', 'account', 'general'])), name='valid_category'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ['low', 'medium', 'high', 'critical'])), name='valid_priority'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['open', 'in_progress', 'resolved', 'closed'])), name='valid_status'),
        ),
    ]
